// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod snakeway {
  pub mod device {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod host {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn config_get(key: &str,) -> Option<_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = key;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "snakeway:device/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "config-get"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result7 = match l3 {
            0 => None,
            1 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l5 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len6 = l5;
                let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                _rt::string_lift(bytes6)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result7
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn log(level: u8,message: &str,) -> (){
        unsafe {
          let vec0 = message;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "snakeway:device/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "log"]
            fn wit_import1(_: i32, _: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(_rt::as_i32(&level), ptr0.cast_mut(), len0);
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn metric_increment(name: &str,delta: u64,) -> (){
        unsafe {
          let vec0 = name;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "snakeway:device/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "metric-increment"]
            fn wit_import1(_: *mut u8, _: usize, _: i64, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, _: i64, ) { unreachable!() }
          wit_import1(ptr0.cast_mut(), len0, _rt::as_i64(&delta));
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn epoch_secs() -> u64{
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "snakeway:device/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "epoch-secs"]
            fn wit_import0() -> i64;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() -> i64 { unreachable!() }
          let ret = wit_import0();
          ret as u64
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[derive(Clone)]
      pub struct Header {
        pub name: _rt::String,
        pub value: _rt::String,
      }
      impl ::core::fmt::Debug for Header {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Header").field("name", &self.name).field("value", &self.value).finish()
        }
      }
      #[derive(Clone)]
      pub enum HeaderOp {
        Set(Header),
        Append(Header),
        Remove(_rt::String),
      }
      impl ::core::fmt::Debug for HeaderOp {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            HeaderOp::Set(e) => {
              f.debug_tuple("HeaderOp::Set").field(e).finish()
            }
            HeaderOp::Append(e) => {
              f.debug_tuple("HeaderOp::Append").field(e).finish()
            }
            HeaderOp::Remove(e) => {
              f.debug_tuple("HeaderOp::Remove").field(e).finish()
            }
          }
        }
      }
      #[derive(Clone)]
      pub struct Request {
        pub method: _rt::String,
        pub scheme: _rt::String,
        pub authority: _rt::String,
        pub original_path: _rt::String,
        pub route_path: _rt::String,
        pub query: _rt::String,
        pub client_ip: _rt::String,
        pub headers: _rt::Vec::<Header>,
      }
      impl ::core::fmt::Debug for Request {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Request").field("method", &self.method).field("scheme", &self.scheme).field("authority", &self.authority).field("original-path", &self.original_path).field("route-path", &self.route_path).field("query", &self.query).field("client-ip", &self.client_ip).field("headers", &self.headers).finish()
        }
      }
      #[derive(Clone)]
      pub struct Response {
        pub status: u16,
        pub headers: _rt::Vec::<Header>,
      }
      impl ::core::fmt::Debug for Response {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Response").field("status", &self.status).field("headers", &self.headers).finish()
        }
      }
      #[derive(Clone)]
      pub struct BodyChunk {
        pub data: _rt::Vec::<u8>,
        pub end_of_stream: bool,
      }
      impl ::core::fmt::Debug for BodyChunk {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("BodyChunk").field("data", &self.data).field("end-of-stream", &self.end_of_stream).finish()
        }
      }
      #[derive(Clone)]
      pub struct SyntheticResponse {
        pub status: u16,
        pub headers: _rt::Vec::<Header>,
        pub body: _rt::Vec::<u8>,
      }
      impl ::core::fmt::Debug for SyntheticResponse {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("SyntheticResponse").field("status", &self.status).field("headers", &self.headers).field("body", &self.body).finish()
        }
      }
      #[derive(Clone)]
      pub enum Action {
        Continue,
        Block,
        Respond(SyntheticResponse),
      }
      impl ::core::fmt::Debug for Action {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            Action::Continue => {
              f.debug_tuple("Action::Continue").finish()
            }
            Action::Block => {
              f.debug_tuple("Action::Block").finish()
            }
            Action::Respond(e) => {
              f.debug_tuple("Action::Respond").field(e).finish()
            }
          }
        }
      }
      #[derive(Clone)]
      pub struct RequestPatch {
        pub set_route_path: Option<_rt::String>,
        pub set_upstream_path: Option<_rt::String>,
        pub ops: _rt::Vec::<HeaderOp>,
      }
      impl ::core::fmt::Debug for RequestPatch {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("RequestPatch").field("set-route-path", &self.set_route_path).field("set-upstream-path", &self.set_upstream_path).field("ops", &self.ops).finish()
        }
      }
      #[derive(Clone)]
      pub struct ResponsePatch {
        pub set_status: Option<u16>,
        pub ops: _rt::Vec::<HeaderOp>,
      }
      impl ::core::fmt::Debug for ResponsePatch {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("ResponsePatch").field("set-status", &self.set_status).field("ops", &self.ops).finish()
        }
      }
      #[derive(Clone)]
      pub struct RequestResult {
        pub action: Action,
        pub patch: Option<RequestPatch>,
      }
      impl ::core::fmt::Debug for RequestResult {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("RequestResult").field("action", &self.action).field("patch", &self.patch).finish()
        }
      }
      #[derive(Clone)]
      pub struct ResponseResult {
        pub action: Action,
        pub patch: Option<ResponsePatch>,
      }
      impl ::core::fmt::Debug for ResponseResult {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("ResponseResult").field("action", &self.action).field("patch", &self.patch).finish()
        }
      }
      #[derive(Clone)]
      pub enum BodyAction {
        Passthrough,
        Replace(_rt::Vec::<u8>),
        Drop,
        Block,
      }
      impl ::core::fmt::Debug for BodyAction {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            BodyAction::Passthrough => {
              f.debug_tuple("BodyAction::Passthrough").finish()
            }
            BodyAction::Replace(e) => {
              f.debug_tuple("BodyAction::Replace").field(e).finish()
            }
            BodyAction::Drop => {
              f.debug_tuple("BodyAction::Drop").finish()
            }
            BodyAction::Block => {
              f.debug_tuple("BodyAction::Block").finish()
            }
          }
        }
      }
      #[derive(Clone)]
      pub struct BodyResult {
        pub action: BodyAction,
      }
      impl ::core::fmt::Debug for BodyResult {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("BodyResult").field("action", &self.action).finish()
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod snakeway {
    pub mod device {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod policy {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type Request = super::super::super::super::snakeway::device::types::Request;
        pub type Response = super::super::super::super::snakeway::device::types::Response;
        pub type BodyChunk = super::super::super::super::snakeway::device::types::BodyChunk;
        pub type RequestResult = super::super::super::super::snakeway::device::types::RequestResult;
        pub type ResponseResult = super::super::super::super::snakeway::device::types::ResponseResult;
        pub type BodyResult = super::super::super::super::snakeway::device::types::BodyResult;
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_on_request_cabi<T: Guest>(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: *mut u8,arg7: usize,arg8: *mut u8,arg9: usize,arg10: *mut u8,arg11: usize,arg12: *mut u8,arg13: usize,arg14: *mut u8,arg15: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result14 = {
          let len0 = arg1;
          let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
          let len1 = arg3;
          let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
          let len2 = arg5;
          let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
          let len3 = arg7;
          let bytes3 = _rt::Vec::from_raw_parts(arg6.cast(), len3, len3);
          let len4 = arg9;
          let bytes4 = _rt::Vec::from_raw_parts(arg8.cast(), len4, len4);
          let len5 = arg11;
          let bytes5 = _rt::Vec::from_raw_parts(arg10.cast(), len5, len5);
          let len6 = arg13;
          let bytes6 = _rt::Vec::from_raw_parts(arg12.cast(), len6, len6);
          let base13 = arg14;
          let len13 = arg15;
          let mut result13 = _rt::Vec::with_capacity(len13);
          for i in 0..len13 {
            let base = base13.add(i * (4*::core::mem::size_of::<*const u8>()));
            let e13 = {
              let l7 = *base.add(0).cast::<*mut u8>();
              let l8 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len9 = l8;
              let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
              let l10 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l11 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len12 = l11;
              let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

              super::super::super::super::snakeway::device::types::Header{
                name: _rt::string_lift(bytes9),
                value: _rt::string_lift(bytes12),
              }
            };
            result13.push(e13);
          }
          _rt::cabi_dealloc(base13, len13 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          T::on_request(super::super::super::super::snakeway::device::types::Request{
            method: _rt::string_lift(bytes0),
            scheme: _rt::string_lift(bytes1),
            authority: _rt::string_lift(bytes2),
            original_path: _rt::string_lift(bytes3),
            route_path: _rt::string_lift(bytes4),
            query: _rt::string_lift(bytes5),
            client_ip: _rt::string_lift(bytes6),
            headers: result13,
          })
        };
        let ptr15 = (&raw mut _RET_AREA.0).cast::<u8>();
        let super::super::super::super::snakeway::device::types::RequestResult{ action:action16, patch:patch16, } = result14;
        use super::super::super::super::snakeway::device::types::Action as V23;
        match action16 {
          V23::Continue=> {
            {
              *ptr15.add(0).cast::<u8>() = (0i32) as u8;
            }
          }
          V23::Block=> {
            {
              *ptr15.add(0).cast::<u8>() = (1i32) as u8;
            }
          }
          V23::Respond(e) => {
            *ptr15.add(0).cast::<u8>() = (2i32) as u8;
            let super::super::super::super::snakeway::device::types::SyntheticResponse{ status:status17, headers:headers17, body:body17, } = e;
            *ptr15.add(::core::mem::size_of::<*const u8>()).cast::<u16>() = (_rt::as_i32(status17)) as u16;
            let vec21 = headers17;
            let len21 = vec21.len();
            let layout21 = _rt::alloc::Layout::from_size_align(vec21.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
            let (result21, _cleanup21) = wit_bindgen::rt::Cleanup::new(layout21);if let Some(cleanup) = _cleanup21 { cleanup.forget(); }
            for (i, e) in vec21.into_iter().enumerate() {
              let base = result21.add(i * (4*::core::mem::size_of::<*const u8>()));
              {
                let super::super::super::super::snakeway::device::types::Header{ name:name18, value:value18, } = e;
                let vec19 = (name18.into_bytes()).into_boxed_slice();
                let ptr19 = vec19.as_ptr().cast::<u8>();
                let len19 = vec19.len();
                ::core::mem::forget(vec19);
                *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len19;
                *base.add(0).cast::<*mut u8>() = ptr19.cast_mut();
                let vec20 = (value18.into_bytes()).into_boxed_slice();
                let ptr20 = vec20.as_ptr().cast::<u8>();
                let len20 = vec20.len();
                ::core::mem::forget(vec20);
                *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len20;
                *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr20.cast_mut();
              }
            }
            *ptr15.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len21;
            *ptr15.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result21;
            let vec22 = <_ as Into<_rt::Vec<_>>>::into(body17).into_boxed_slice();
            let ptr22 = vec22.as_ptr().cast::<u8>();
            let len22 = vec22.len();
            ::core::mem::forget(vec22);
            *ptr15.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len22;
            *ptr15.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr22.cast_mut();
          },
        }
        match patch16 {
          Some(e) => {
            *ptr15.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let super::super::super::super::snakeway::device::types::RequestPatch{ set_route_path:set_route_path24, set_upstream_path:set_upstream_path24, ops:ops24, } = e;
            match set_route_path24 {
              Some(e) => {
                *ptr15.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                let vec25 = (e.into_bytes()).into_boxed_slice();
                let ptr25 = vec25.as_ptr().cast::<u8>();
                let len25 = vec25.len();
                ::core::mem::forget(vec25);
                *ptr15.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>() = len25;
                *ptr15.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr25.cast_mut();
              },
              None => {
                {
                  *ptr15.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                }
              },
            };match set_upstream_path24 {
              Some(e) => {
                *ptr15.add(10*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                let vec26 = (e.into_bytes()).into_boxed_slice();
                let ptr26 = vec26.as_ptr().cast::<u8>();
                let len26 = vec26.len();
                ::core::mem::forget(vec26);
                *ptr15.add(12*::core::mem::size_of::<*const u8>()).cast::<usize>() = len26;
                *ptr15.add(11*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr26.cast_mut();
              },
              None => {
                {
                  *ptr15.add(10*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                }
              },
            };let vec35 = ops24;
            let len35 = vec35.len();
            let layout35 = _rt::alloc::Layout::from_size_align(vec35.len() * (5*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
            let (result35, _cleanup35) = wit_bindgen::rt::Cleanup::new(layout35);if let Some(cleanup) = _cleanup35 { cleanup.forget(); }
            for (i, e) in vec35.into_iter().enumerate() {
              let base = result35.add(i * (5*::core::mem::size_of::<*const u8>()));
              {
                use super::super::super::super::snakeway::device::types::HeaderOp as V34;
                match e {
                  V34::Set(e) => {
                    *base.add(0).cast::<u8>() = (0i32) as u8;
                    let super::super::super::super::snakeway::device::types::Header{ name:name27, value:value27, } = e;
                    let vec28 = (name27.into_bytes()).into_boxed_slice();
                    let ptr28 = vec28.as_ptr().cast::<u8>();
                    let len28 = vec28.len();
                    ::core::mem::forget(vec28);
                    *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len28;
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr28.cast_mut();
                    let vec29 = (value27.into_bytes()).into_boxed_slice();
                    let ptr29 = vec29.as_ptr().cast::<u8>();
                    let len29 = vec29.len();
                    ::core::mem::forget(vec29);
                    *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len29;
                    *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr29.cast_mut();
                  },
                  V34::Append(e) => {
                    *base.add(0).cast::<u8>() = (1i32) as u8;
                    let super::super::super::super::snakeway::device::types::Header{ name:name30, value:value30, } = e;
                    let vec31 = (name30.into_bytes()).into_boxed_slice();
                    let ptr31 = vec31.as_ptr().cast::<u8>();
                    let len31 = vec31.len();
                    ::core::mem::forget(vec31);
                    *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len31;
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr31.cast_mut();
                    let vec32 = (value30.into_bytes()).into_boxed_slice();
                    let ptr32 = vec32.as_ptr().cast::<u8>();
                    let len32 = vec32.len();
                    ::core::mem::forget(vec32);
                    *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len32;
                    *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr32.cast_mut();
                  },
                  V34::Remove(e) => {
                    *base.add(0).cast::<u8>() = (2i32) as u8;
                    let vec33 = (e.into_bytes()).into_boxed_slice();
                    let ptr33 = vec33.as_ptr().cast::<u8>();
                    let len33 = vec33.len();
                    ::core::mem::forget(vec33);
                    *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len33;
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr33.cast_mut();
                  },
                }
              }
            }
            *ptr15.add(14*::core::mem::size_of::<*const u8>()).cast::<usize>() = len35;
            *ptr15.add(13*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result35;
          },
          None => {
            {
              *ptr15.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };ptr15
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_on_request<T: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = i32::from(*arg0.add(0).cast::<u8>());
        match l0 {
          0 => (),
          1 => (),
          _ => {
            let l1 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base7 = l1;
            let len7 = l2;
            for i in 0..len7 {
              let base = base7.add(i * (4*::core::mem::size_of::<*const u8>()));
              {
                let l3 = *base.add(0).cast::<*mut u8>();
                let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l3, l4, 1);
                let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l5, l6, 1);
              }
            }
            _rt::cabi_dealloc(base7, len7 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
            let l8 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l9 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base10 = l8;
            let len10 = l9;
            _rt::cabi_dealloc(base10, len10 * 1, 1);
          },
        }
        let l11 = i32::from(*arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>());
        match l11 {
          0 => (),
          _ => {
            let l12 = i32::from(*arg0.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>());
            match l12 {
              0 => (),
              _ => {
                let l13 = *arg0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l14 = *arg0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l13, l14, 1);
              },
            }
            let l15 = i32::from(*arg0.add(10*::core::mem::size_of::<*const u8>()).cast::<u8>());
            match l15 {
              0 => (),
              _ => {
                let l16 = *arg0.add(11*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l17 = *arg0.add(12*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l16, l17, 1);
              },
            }
            let l18 = *arg0.add(13*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l19 = *arg0.add(14*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base31 = l18;
            let len31 = l19;
            for i in 0..len31 {
              let base = base31.add(i * (5*::core::mem::size_of::<*const u8>()));
              {
                let l20 = i32::from(*base.add(0).cast::<u8>());
                match l20 {
                  0 => {
                    let l21 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                    let l22 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                    _rt::cabi_dealloc(l21, l22, 1);
                    let l23 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                    let l24 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                    _rt::cabi_dealloc(l23, l24, 1);
                  },
                  1 => {
                    let l25 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                    let l26 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                    _rt::cabi_dealloc(l25, l26, 1);
                    let l27 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                    let l28 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                    _rt::cabi_dealloc(l27, l28, 1);
                  },
                  _ => {
                    let l29 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                    let l30 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                    _rt::cabi_dealloc(l29, l30, 1);
                  },
                }
              }
            }
            _rt::cabi_dealloc(base31, len31 * (5*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          },
        }
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_on_stream_request_body_cabi<T: Guest>(arg0: *mut u8,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result35 = {
        let l0 = *arg0.add(0).cast::<*mut u8>();
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len2 = l1;
        let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
        let l3 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l4 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len5 = l4;
        let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
        let l6 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l7 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len8 = l7;
        let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
        let l9 = *arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l10 = *arg0.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len11 = l10;
        let bytes11 = _rt::Vec::from_raw_parts(l9.cast(), len11, len11);
        let l12 = *arg0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l13 = *arg0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len14 = l13;
        let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);
        let l15 = *arg0.add(10*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l16 = *arg0.add(11*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len17 = l16;
        let bytes17 = _rt::Vec::from_raw_parts(l15.cast(), len17, len17);
        let l18 = *arg0.add(12*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l19 = *arg0.add(13*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len20 = l19;
        let bytes20 = _rt::Vec::from_raw_parts(l18.cast(), len20, len20);
        let l21 = *arg0.add(14*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l22 = *arg0.add(15*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base29 = l21;
        let len29 = l22;
        let mut result29 = _rt::Vec::with_capacity(len29);
        for i in 0..len29 {
          let base = base29.add(i * (4*::core::mem::size_of::<*const u8>()));
          let e29 = {
            let l23 = *base.add(0).cast::<*mut u8>();
            let l24 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len25 = l24;
            let bytes25 = _rt::Vec::from_raw_parts(l23.cast(), len25, len25);
            let l26 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l27 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len28 = l27;
            let bytes28 = _rt::Vec::from_raw_parts(l26.cast(), len28, len28);

            super::super::super::super::snakeway::device::types::Header{
              name: _rt::string_lift(bytes25),
              value: _rt::string_lift(bytes28),
            }
          };
          result29.push(e29);
        }
        _rt::cabi_dealloc(base29, len29 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        let l30 = i32::from(*arg0.add(16*::core::mem::size_of::<*const u8>()).cast::<u8>());
        T::on_stream_request_body(super::super::super::super::snakeway::device::types::Request{
          method: _rt::string_lift(bytes2),
          scheme: _rt::string_lift(bytes5),
          authority: _rt::string_lift(bytes8),
          original_path: _rt::string_lift(bytes11),
          route_path: _rt::string_lift(bytes14),
          query: _rt::string_lift(bytes17),
          client_ip: _rt::string_lift(bytes20),
          headers: result29,
        }, match l30 {
          0 => None,
          1 => {
            let e = {
              let l31 = *arg0.add(17*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l32 = *arg0.add(18*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len33 = l32;
              let l34 = i32::from(*arg0.add(19*::core::mem::size_of::<*const u8>()).cast::<u8>());

              super::super::super::super::snakeway::device::types::BodyChunk{
                data: <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l31.cast(), len33, len33)),
                end_of_stream: _rt::bool_lift(l34 as u8),
              }
            };
            Some(e)
          }
          _ => _rt::invalid_enum_discriminant(),
        })
      };
      _rt::cabi_dealloc(arg0, 20*::core::mem::size_of::<*const u8>(), ::core::mem::size_of::<*const u8>());
      let ptr36 = (&raw mut _RET_AREA.0).cast::<u8>();
      let super::super::super::super::snakeway::device::types::BodyResult{ action:action37, } = result35;
      use super::super::super::super::snakeway::device::types::BodyAction as V39;
      match action37 {
        V39::Passthrough=> {
          {
            *ptr36.add(0).cast::<u8>() = (0i32) as u8;
          }
        }
        V39::Replace(e) => {
          *ptr36.add(0).cast::<u8>() = (1i32) as u8;
          let vec38 = <_ as Into<_rt::Vec<_>>>::into(e).into_boxed_slice();
          let ptr38 = vec38.as_ptr().cast::<u8>();
          let len38 = vec38.len();
          ::core::mem::forget(vec38);
          *ptr36.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len38;
          *ptr36.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr38.cast_mut();
        },
        V39::Drop=> {
          {
            *ptr36.add(0).cast::<u8>() = (2i32) as u8;
          }
        }
        V39::Block=> {
          {
            *ptr36.add(0).cast::<u8>() = (3i32) as u8;
          }
        }
      }
      ptr36
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_on_stream_request_body<T: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => (),
        1 => {
          let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base3 = l1;
          let len3 = l2;
          _rt::cabi_dealloc(base3, len3 * 1, 1);
        },
        2 => (),
        _ => (),
      }
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_before_proxy_cabi<T: Guest>(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: *mut u8,arg7: usize,arg8: *mut u8,arg9: usize,arg10: *mut u8,arg11: usize,arg12: *mut u8,arg13: usize,arg14: *mut u8,arg15: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();let result14 = {
      let len0 = arg1;
      let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
      let len1 = arg3;
      let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
      let len2 = arg5;
      let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
      let len3 = arg7;
      let bytes3 = _rt::Vec::from_raw_parts(arg6.cast(), len3, len3);
      let len4 = arg9;
      let bytes4 = _rt::Vec::from_raw_parts(arg8.cast(), len4, len4);
      let len5 = arg11;
      let bytes5 = _rt::Vec::from_raw_parts(arg10.cast(), len5, len5);
      let len6 = arg13;
      let bytes6 = _rt::Vec::from_raw_parts(arg12.cast(), len6, len6);
      let base13 = arg14;
      let len13 = arg15;
      let mut result13 = _rt::Vec::with_capacity(len13);
      for i in 0..len13 {
        let base = base13.add(i * (4*::core::mem::size_of::<*const u8>()));
        let e13 = {
          let l7 = *base.add(0).cast::<*mut u8>();
          let l8 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len9 = l8;
          let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
          let l10 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l11 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len12 = l11;
          let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

          super::super::super::super::snakeway::device::types::Header{
            name: _rt::string_lift(bytes9),
            value: _rt::string_lift(bytes12),
          }
        };
        result13.push(e13);
      }
      _rt::cabi_dealloc(base13, len13 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      T::before_proxy(super::super::super::super::snakeway::device::types::Request{
        method: _rt::string_lift(bytes0),
        scheme: _rt::string_lift(bytes1),
        authority: _rt::string_lift(bytes2),
        original_path: _rt::string_lift(bytes3),
        route_path: _rt::string_lift(bytes4),
        query: _rt::string_lift(bytes5),
        client_ip: _rt::string_lift(bytes6),
        headers: result13,
      })
    };
    let ptr15 = (&raw mut _RET_AREA.0).cast::<u8>();
    let super::super::super::super::snakeway::device::types::RequestResult{ action:action16, patch:patch16, } = result14;
    use super::super::super::super::snakeway::device::types::Action as V23;
    match action16 {
      V23::Continue=> {
        {
          *ptr15.add(0).cast::<u8>() = (0i32) as u8;
        }
      }
      V23::Block=> {
        {
          *ptr15.add(0).cast::<u8>() = (1i32) as u8;
        }
      }
      V23::Respond(e) => {
        *ptr15.add(0).cast::<u8>() = (2i32) as u8;
        let super::super::super::super::snakeway::device::types::SyntheticResponse{ status:status17, headers:headers17, body:body17, } = e;
        *ptr15.add(::core::mem::size_of::<*const u8>()).cast::<u16>() = (_rt::as_i32(status17)) as u16;
        let vec21 = headers17;
        let len21 = vec21.len();
        let layout21 = _rt::alloc::Layout::from_size_align(vec21.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result21, _cleanup21) = wit_bindgen::rt::Cleanup::new(layout21);if let Some(cleanup) = _cleanup21 { cleanup.forget(); }
        for (i, e) in vec21.into_iter().enumerate() {
          let base = result21.add(i * (4*::core::mem::size_of::<*const u8>()));
          {
            let super::super::super::super::snakeway::device::types::Header{ name:name18, value:value18, } = e;
            let vec19 = (name18.into_bytes()).into_boxed_slice();
            let ptr19 = vec19.as_ptr().cast::<u8>();
            let len19 = vec19.len();
            ::core::mem::forget(vec19);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len19;
            *base.add(0).cast::<*mut u8>() = ptr19.cast_mut();
            let vec20 = (value18.into_bytes()).into_boxed_slice();
            let ptr20 = vec20.as_ptr().cast::<u8>();
            let len20 = vec20.len();
            ::core::mem::forget(vec20);
            *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len20;
            *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr20.cast_mut();
          }
        }
        *ptr15.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len21;
        *ptr15.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result21;
        let vec22 = <_ as Into<_rt::Vec<_>>>::into(body17).into_boxed_slice();
        let ptr22 = vec22.as_ptr().cast::<u8>();
        let len22 = vec22.len();
        ::core::mem::forget(vec22);
        *ptr15.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len22;
        *ptr15.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr22.cast_mut();
      },
    }
    match patch16 {
      Some(e) => {
        *ptr15.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
        let super::super::super::super::snakeway::device::types::RequestPatch{ set_route_path:set_route_path24, set_upstream_path:set_upstream_path24, ops:ops24, } = e;
        match set_route_path24 {
          Some(e) => {
            *ptr15.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec25 = (e.into_bytes()).into_boxed_slice();
            let ptr25 = vec25.as_ptr().cast::<u8>();
            let len25 = vec25.len();
            ::core::mem::forget(vec25);
            *ptr15.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>() = len25;
            *ptr15.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr25.cast_mut();
          },
          None => {
            {
              *ptr15.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };match set_upstream_path24 {
          Some(e) => {
            *ptr15.add(10*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let vec26 = (e.into_bytes()).into_boxed_slice();
            let ptr26 = vec26.as_ptr().cast::<u8>();
            let len26 = vec26.len();
            ::core::mem::forget(vec26);
            *ptr15.add(12*::core::mem::size_of::<*const u8>()).cast::<usize>() = len26;
            *ptr15.add(11*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr26.cast_mut();
          },
          None => {
            {
              *ptr15.add(10*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };let vec35 = ops24;
        let len35 = vec35.len();
        let layout35 = _rt::alloc::Layout::from_size_align(vec35.len() * (5*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result35, _cleanup35) = wit_bindgen::rt::Cleanup::new(layout35);if let Some(cleanup) = _cleanup35 { cleanup.forget(); }
        for (i, e) in vec35.into_iter().enumerate() {
          let base = result35.add(i * (5*::core::mem::size_of::<*const u8>()));
          {
            use super::super::super::super::snakeway::device::types::HeaderOp as V34;
            match e {
              V34::Set(e) => {
                *base.add(0).cast::<u8>() = (0i32) as u8;
                let super::super::super::super::snakeway::device::types::Header{ name:name27, value:value27, } = e;
                let vec28 = (name27.into_bytes()).into_boxed_slice();
                let ptr28 = vec28.as_ptr().cast::<u8>();
                let len28 = vec28.len();
                ::core::mem::forget(vec28);
                *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len28;
                *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr28.cast_mut();
                let vec29 = (value27.into_bytes()).into_boxed_slice();
                let ptr29 = vec29.as_ptr().cast::<u8>();
                let len29 = vec29.len();
                ::core::mem::forget(vec29);
                *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len29;
                *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr29.cast_mut();
              },
              V34::Append(e) => {
                *base.add(0).cast::<u8>() = (1i32) as u8;
                let super::super::super::super::snakeway::device::types::Header{ name:name30, value:value30, } = e;
                let vec31 = (name30.into_bytes()).into_boxed_slice();
                let ptr31 = vec31.as_ptr().cast::<u8>();
                let len31 = vec31.len();
                ::core::mem::forget(vec31);
                *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len31;
                *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr31.cast_mut();
                let vec32 = (value30.into_bytes()).into_boxed_slice();
                let ptr32 = vec32.as_ptr().cast::<u8>();
                let len32 = vec32.len();
                ::core::mem::forget(vec32);
                *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len32;
                *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr32.cast_mut();
              },
              V34::Remove(e) => {
                *base.add(0).cast::<u8>() = (2i32) as u8;
                let vec33 = (e.into_bytes()).into_boxed_slice();
                let ptr33 = vec33.as_ptr().cast::<u8>();
                let len33 = vec33.len();
                ::core::mem::forget(vec33);
                *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len33;
                *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr33.cast_mut();
              },
            }
          }
        }
        *ptr15.add(14*::core::mem::size_of::<*const u8>()).cast::<usize>() = len35;
        *ptr15.add(13*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result35;
      },
      None => {
        {
          *ptr15.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
        }
      },
    };ptr15
  } }
  #[doc(hidden)]
  #[allow(non_snake_case)]
  pub unsafe fn __post_return_before_proxy<T: Guest>(arg0: *mut u8,) { unsafe {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
      0 => (),
      1 => (),
      _ => {
        let l1 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l2 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base7 = l1;
        let len7 = l2;
        for i in 0..len7 {
          let base = base7.add(i * (4*::core::mem::size_of::<*const u8>()));
          {
            let l3 = *base.add(0).cast::<*mut u8>();
            let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
            let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l5, l6, 1);
          }
        }
        _rt::cabi_dealloc(base7, len7 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        let l8 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l9 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base10 = l8;
        let len10 = l9;
        _rt::cabi_dealloc(base10, len10 * 1, 1);
      },
    }
    let l11 = i32::from(*arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>());
    match l11 {
      0 => (),
      _ => {
        let l12 = i32::from(*arg0.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>());
        match l12 {
          0 => (),
          _ => {
            let l13 = *arg0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l14 = *arg0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l13, l14, 1);
          },
        }
        let l15 = i32::from(*arg0.add(10*::core::mem::size_of::<*const u8>()).cast::<u8>());
        match l15 {
          0 => (),
          _ => {
            let l16 = *arg0.add(11*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l17 = *arg0.add(12*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l16, l17, 1);
          },
        }
        let l18 = *arg0.add(13*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l19 = *arg0.add(14*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base31 = l18;
        let len31 = l19;
        for i in 0..len31 {
          let base = base31.add(i * (5*::core::mem::size_of::<*const u8>()));
          {
            let l20 = i32::from(*base.add(0).cast::<u8>());
            match l20 {
              0 => {
                let l21 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l22 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l21, l22, 1);
                let l23 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l24 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l23, l24, 1);
              },
              1 => {
                let l25 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l26 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l25, l26, 1);
                let l27 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l28 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l27, l28, 1);
              },
              _ => {
                let l29 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l30 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l29, l30, 1);
              },
            }
          }
        }
        _rt::cabi_dealloc(base31, len31 * (5*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      },
    }
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_after_proxy_cabi<T: Guest>(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();let result7 = {
    let base6 = arg1;
    let len6 = arg2;
    let mut result6 = _rt::Vec::with_capacity(len6);
    for i in 0..len6 {
      let base = base6.add(i * (4*::core::mem::size_of::<*const u8>()));
      let e6 = {
        let l0 = *base.add(0).cast::<*mut u8>();
        let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len2 = l1;
        let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
        let l3 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l4 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len5 = l4;
        let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

        super::super::super::super::snakeway::device::types::Header{
          name: _rt::string_lift(bytes2),
          value: _rt::string_lift(bytes5),
        }
      };
      result6.push(e6);
    }
    _rt::cabi_dealloc(base6, len6 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    T::after_proxy(super::super::super::super::snakeway::device::types::Response{
      status: arg0 as u16,
      headers: result6,
    })
  };
  let ptr8 = (&raw mut _RET_AREA.0).cast::<u8>();
  let super::super::super::super::snakeway::device::types::ResponseResult{ action:action9, patch:patch9, } = result7;
  use super::super::super::super::snakeway::device::types::Action as V16;
  match action9 {
    V16::Continue=> {
      {
        *ptr8.add(0).cast::<u8>() = (0i32) as u8;
      }
    }
    V16::Block=> {
      {
        *ptr8.add(0).cast::<u8>() = (1i32) as u8;
      }
    }
    V16::Respond(e) => {
      *ptr8.add(0).cast::<u8>() = (2i32) as u8;
      let super::super::super::super::snakeway::device::types::SyntheticResponse{ status:status10, headers:headers10, body:body10, } = e;
      *ptr8.add(::core::mem::size_of::<*const u8>()).cast::<u16>() = (_rt::as_i32(status10)) as u16;
      let vec14 = headers10;
      let len14 = vec14.len();
      let layout14 = _rt::alloc::Layout::from_size_align(vec14.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
      let (result14, _cleanup14) = wit_bindgen::rt::Cleanup::new(layout14);if let Some(cleanup) = _cleanup14 { cleanup.forget(); }
      for (i, e) in vec14.into_iter().enumerate() {
        let base = result14.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let super::super::super::super::snakeway::device::types::Header{ name:name11, value:value11, } = e;
          let vec12 = (name11.into_bytes()).into_boxed_slice();
          let ptr12 = vec12.as_ptr().cast::<u8>();
          let len12 = vec12.len();
          ::core::mem::forget(vec12);
          *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len12;
          *base.add(0).cast::<*mut u8>() = ptr12.cast_mut();
          let vec13 = (value11.into_bytes()).into_boxed_slice();
          let ptr13 = vec13.as_ptr().cast::<u8>();
          let len13 = vec13.len();
          ::core::mem::forget(vec13);
          *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
          *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr13.cast_mut();
        }
      }
      *ptr8.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
      *ptr8.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result14;
      let vec15 = <_ as Into<_rt::Vec<_>>>::into(body10).into_boxed_slice();
      let ptr15 = vec15.as_ptr().cast::<u8>();
      let len15 = vec15.len();
      ::core::mem::forget(vec15);
      *ptr8.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
      *ptr8.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr15.cast_mut();
    },
  }
  match patch9 {
    Some(e) => {
      *ptr8.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
      let super::super::super::super::snakeway::device::types::ResponsePatch{ set_status:set_status17, ops:ops17, } = e;
      match set_status17 {
        Some(e) => {
          *ptr8.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
          *ptr8.add(2+7*::core::mem::size_of::<*const u8>()).cast::<u16>() = (_rt::as_i32(e)) as u16;
        },
        None => {
          {
            *ptr8.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
          }
        },
      };let vec26 = ops17;
      let len26 = vec26.len();
      let layout26 = _rt::alloc::Layout::from_size_align(vec26.len() * (5*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
      let (result26, _cleanup26) = wit_bindgen::rt::Cleanup::new(layout26);if let Some(cleanup) = _cleanup26 { cleanup.forget(); }
      for (i, e) in vec26.into_iter().enumerate() {
        let base = result26.add(i * (5*::core::mem::size_of::<*const u8>()));
        {
          use super::super::super::super::snakeway::device::types::HeaderOp as V25;
          match e {
            V25::Set(e) => {
              *base.add(0).cast::<u8>() = (0i32) as u8;
              let super::super::super::super::snakeway::device::types::Header{ name:name18, value:value18, } = e;
              let vec19 = (name18.into_bytes()).into_boxed_slice();
              let ptr19 = vec19.as_ptr().cast::<u8>();
              let len19 = vec19.len();
              ::core::mem::forget(vec19);
              *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len19;
              *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr19.cast_mut();
              let vec20 = (value18.into_bytes()).into_boxed_slice();
              let ptr20 = vec20.as_ptr().cast::<u8>();
              let len20 = vec20.len();
              ::core::mem::forget(vec20);
              *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len20;
              *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr20.cast_mut();
            },
            V25::Append(e) => {
              *base.add(0).cast::<u8>() = (1i32) as u8;
              let super::super::super::super::snakeway::device::types::Header{ name:name21, value:value21, } = e;
              let vec22 = (name21.into_bytes()).into_boxed_slice();
              let ptr22 = vec22.as_ptr().cast::<u8>();
              let len22 = vec22.len();
              ::core::mem::forget(vec22);
              *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len22;
              *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr22.cast_mut();
              let vec23 = (value21.into_bytes()).into_boxed_slice();
              let ptr23 = vec23.as_ptr().cast::<u8>();
              let len23 = vec23.len();
              ::core::mem::forget(vec23);
              *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len23;
              *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr23.cast_mut();
            },
            V25::Remove(e) => {
              *base.add(0).cast::<u8>() = (2i32) as u8;
              let vec24 = (e.into_bytes()).into_boxed_slice();
              let ptr24 = vec24.as_ptr().cast::<u8>();
              let len24 = vec24.len();
              ::core::mem::forget(vec24);
              *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len24;
              *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr24.cast_mut();
            },
          }
        }
      }
      *ptr8.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>() = len26;
      *ptr8.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result26;
    },
    None => {
      {
        *ptr8.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
      }
    },
  };ptr8
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_after_proxy<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    1 => (),
    _ => {
      let l1 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base7 = l1;
      let len7 = l2;
      for i in 0..len7 {
        let base = base7.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let l3 = *base.add(0).cast::<*mut u8>();
          let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l3, l4, 1);
          let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l5, l6, 1);
        }
      }
      _rt::cabi_dealloc(base7, len7 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      let l8 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l9 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base10 = l8;
      let len10 = l9;
      _rt::cabi_dealloc(base10, len10 * 1, 1);
    },
  }
  let l11 = i32::from(*arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>());
  match l11 {
    0 => (),
    _ => {
      let l12 = *arg0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l13 = *arg0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base25 = l12;
      let len25 = l13;
      for i in 0..len25 {
        let base = base25.add(i * (5*::core::mem::size_of::<*const u8>()));
        {
          let l14 = i32::from(*base.add(0).cast::<u8>());
          match l14 {
            0 => {
              let l15 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l16 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l15, l16, 1);
              let l17 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l18 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l17, l18, 1);
            },
            1 => {
              let l19 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l20 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l19, l20, 1);
              let l21 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l22 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l21, l22, 1);
            },
            _ => {
              let l23 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l24 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l23, l24, 1);
            },
          }
        }
      }
      _rt::cabi_dealloc(base25, len25 * (5*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    },
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_on_stream_response_body_cabi<T: Guest>(arg0: i32,arg1: *mut u8,arg2: usize,arg3: i32,arg4: *mut u8,arg5: usize,arg6: i32,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result8 = {
  let base6 = arg1;
  let len6 = arg2;
  let mut result6 = _rt::Vec::with_capacity(len6);
  for i in 0..len6 {
    let base = base6.add(i * (4*::core::mem::size_of::<*const u8>()));
    let e6 = {
      let l0 = *base.add(0).cast::<*mut u8>();
      let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
      let len2 = l1;
      let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
      let l3 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l4 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let len5 = l4;
      let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

      super::super::super::super::snakeway::device::types::Header{
        name: _rt::string_lift(bytes2),
        value: _rt::string_lift(bytes5),
      }
    };
    result6.push(e6);
  }
  _rt::cabi_dealloc(base6, len6 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
  T::on_stream_response_body(super::super::super::super::snakeway::device::types::Response{
    status: arg0 as u16,
    headers: result6,
  }, match arg3 {
    0 => None,
    1 => {
      let e = {
        let len7 = arg5;

        super::super::super::super::snakeway::device::types::BodyChunk{
          data: <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(arg4.cast(), len7, len7)),
          end_of_stream: _rt::bool_lift(arg6 as u8),
        }
      };
      Some(e)
    }
    _ => _rt::invalid_enum_discriminant(),
  })
};
let ptr9 = (&raw mut _RET_AREA.0).cast::<u8>();
let super::super::super::super::snakeway::device::types::BodyResult{ action:action10, } = result8;
use super::super::super::super::snakeway::device::types::BodyAction as V12;
match action10 {
  V12::Passthrough=> {
    {
      *ptr9.add(0).cast::<u8>() = (0i32) as u8;
    }
  }
  V12::Replace(e) => {
    *ptr9.add(0).cast::<u8>() = (1i32) as u8;
    let vec11 = <_ as Into<_rt::Vec<_>>>::into(e).into_boxed_slice();
    let ptr11 = vec11.as_ptr().cast::<u8>();
    let len11 = vec11.len();
    ::core::mem::forget(vec11);
    *ptr9.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len11;
    *ptr9.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr11.cast_mut();
  },
  V12::Drop=> {
    {
      *ptr9.add(0).cast::<u8>() = (2i32) as u8;
    }
  }
  V12::Block=> {
    {
      *ptr9.add(0).cast::<u8>() = (3i32) as u8;
    }
  }
}
ptr9
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_on_stream_response_body<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    1 => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base3 = l1;
      let len3 = l2;
      _rt::cabi_dealloc(base3, len3 * 1, 1);
    },
    2 => (),
    _ => (),
  }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_on_response_cabi<T: Guest>(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result7 = {
  let base6 = arg1;
  let len6 = arg2;
  let mut result6 = _rt::Vec::with_capacity(len6);
  for i in 0..len6 {
    let base = base6.add(i * (4*::core::mem::size_of::<*const u8>()));
    let e6 = {
      let l0 = *base.add(0).cast::<*mut u8>();
      let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
      let len2 = l1;
      let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
      let l3 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l4 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let len5 = l4;
      let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

      super::super::super::super::snakeway::device::types::Header{
        name: _rt::string_lift(bytes2),
        value: _rt::string_lift(bytes5),
      }
    };
    result6.push(e6);
  }
  _rt::cabi_dealloc(base6, len6 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
  T::on_response(super::super::super::super::snakeway::device::types::Response{
    status: arg0 as u16,
    headers: result6,
  })
};
let ptr8 = (&raw mut _RET_AREA.0).cast::<u8>();
let super::super::super::super::snakeway::device::types::ResponseResult{ action:action9, patch:patch9, } = result7;
use super::super::super::super::snakeway::device::types::Action as V16;
match action9 {
  V16::Continue=> {
    {
      *ptr8.add(0).cast::<u8>() = (0i32) as u8;
    }
  }
  V16::Block=> {
    {
      *ptr8.add(0).cast::<u8>() = (1i32) as u8;
    }
  }
  V16::Respond(e) => {
    *ptr8.add(0).cast::<u8>() = (2i32) as u8;
    let super::super::super::super::snakeway::device::types::SyntheticResponse{ status:status10, headers:headers10, body:body10, } = e;
    *ptr8.add(::core::mem::size_of::<*const u8>()).cast::<u16>() = (_rt::as_i32(status10)) as u16;
    let vec14 = headers10;
    let len14 = vec14.len();
    let layout14 = _rt::alloc::Layout::from_size_align(vec14.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
    let (result14, _cleanup14) = wit_bindgen::rt::Cleanup::new(layout14);if let Some(cleanup) = _cleanup14 { cleanup.forget(); }
    for (i, e) in vec14.into_iter().enumerate() {
      let base = result14.add(i * (4*::core::mem::size_of::<*const u8>()));
      {
        let super::super::super::super::snakeway::device::types::Header{ name:name11, value:value11, } = e;
        let vec12 = (name11.into_bytes()).into_boxed_slice();
        let ptr12 = vec12.as_ptr().cast::<u8>();
        let len12 = vec12.len();
        ::core::mem::forget(vec12);
        *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len12;
        *base.add(0).cast::<*mut u8>() = ptr12.cast_mut();
        let vec13 = (value11.into_bytes()).into_boxed_slice();
        let ptr13 = vec13.as_ptr().cast::<u8>();
        let len13 = vec13.len();
        ::core::mem::forget(vec13);
        *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
        *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr13.cast_mut();
      }
    }
    *ptr8.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
    *ptr8.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result14;
    let vec15 = <_ as Into<_rt::Vec<_>>>::into(body10).into_boxed_slice();
    let ptr15 = vec15.as_ptr().cast::<u8>();
    let len15 = vec15.len();
    ::core::mem::forget(vec15);
    *ptr8.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
    *ptr8.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr15.cast_mut();
  },
}
match patch9 {
  Some(e) => {
    *ptr8.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
    let super::super::super::super::snakeway::device::types::ResponsePatch{ set_status:set_status17, ops:ops17, } = e;
    match set_status17 {
      Some(e) => {
        *ptr8.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
        *ptr8.add(2+7*::core::mem::size_of::<*const u8>()).cast::<u16>() = (_rt::as_i32(e)) as u16;
      },
      None => {
        {
          *ptr8.add(7*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
        }
      },
    };let vec26 = ops17;
    let len26 = vec26.len();
    let layout26 = _rt::alloc::Layout::from_size_align(vec26.len() * (5*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
    let (result26, _cleanup26) = wit_bindgen::rt::Cleanup::new(layout26);if let Some(cleanup) = _cleanup26 { cleanup.forget(); }
    for (i, e) in vec26.into_iter().enumerate() {
      let base = result26.add(i * (5*::core::mem::size_of::<*const u8>()));
      {
        use super::super::super::super::snakeway::device::types::HeaderOp as V25;
        match e {
          V25::Set(e) => {
            *base.add(0).cast::<u8>() = (0i32) as u8;
            let super::super::super::super::snakeway::device::types::Header{ name:name18, value:value18, } = e;
            let vec19 = (name18.into_bytes()).into_boxed_slice();
            let ptr19 = vec19.as_ptr().cast::<u8>();
            let len19 = vec19.len();
            ::core::mem::forget(vec19);
            *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len19;
            *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr19.cast_mut();
            let vec20 = (value18.into_bytes()).into_boxed_slice();
            let ptr20 = vec20.as_ptr().cast::<u8>();
            let len20 = vec20.len();
            ::core::mem::forget(vec20);
            *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len20;
            *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr20.cast_mut();
          },
          V25::Append(e) => {
            *base.add(0).cast::<u8>() = (1i32) as u8;
            let super::super::super::super::snakeway::device::types::Header{ name:name21, value:value21, } = e;
            let vec22 = (name21.into_bytes()).into_boxed_slice();
            let ptr22 = vec22.as_ptr().cast::<u8>();
            let len22 = vec22.len();
            ::core::mem::forget(vec22);
            *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len22;
            *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr22.cast_mut();
            let vec23 = (value21.into_bytes()).into_boxed_slice();
            let ptr23 = vec23.as_ptr().cast::<u8>();
            let len23 = vec23.len();
            ::core::mem::forget(vec23);
            *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len23;
            *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr23.cast_mut();
          },
          V25::Remove(e) => {
            *base.add(0).cast::<u8>() = (2i32) as u8;
            let vec24 = (e.into_bytes()).into_boxed_slice();
            let ptr24 = vec24.as_ptr().cast::<u8>();
            let len24 = vec24.len();
            ::core::mem::forget(vec24);
            *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len24;
            *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr24.cast_mut();
          },
        }
      }
    }
    *ptr8.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>() = len26;
    *ptr8.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result26;
  },
  None => {
    {
      *ptr8.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr8
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_on_response<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    1 => (),
    _ => {
      let l1 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base7 = l1;
      let len7 = l2;
      for i in 0..len7 {
        let base = base7.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let l3 = *base.add(0).cast::<*mut u8>();
          let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l3, l4, 1);
          let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l5, l6, 1);
        }
      }
      _rt::cabi_dealloc(base7, len7 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      let l8 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l9 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base10 = l8;
      let len10 = l9;
      _rt::cabi_dealloc(base10, len10 * 1, 1);
    },
  }
  let l11 = i32::from(*arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<u8>());
  match l11 {
    0 => (),
    _ => {
      let l12 = *arg0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l13 = *arg0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base25 = l12;
      let len25 = l13;
      for i in 0..len25 {
        let base = base25.add(i * (5*::core::mem::size_of::<*const u8>()));
        {
          let l14 = i32::from(*base.add(0).cast::<u8>());
          match l14 {
            0 => {
              let l15 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l16 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l15, l16, 1);
              let l17 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l18 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l17, l18, 1);
            },
            1 => {
              let l19 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l20 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l19, l20, 1);
              let l21 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l22 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l21, l22, 1);
            },
            _ => {
              let l23 = *base.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l24 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l23, l24, 1);
            },
          }
        }
      }
      _rt::cabi_dealloc(base25, len25 * (5*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    },
  }
} }
pub trait Guest {
  #[allow(async_fn_in_trait)]
  fn on_request(req: Request,) -> RequestResult;
  #[allow(async_fn_in_trait)]
  fn on_stream_request_body(req: Request,chunk: Option<BodyChunk>,) -> BodyResult;
  #[allow(async_fn_in_trait)]
  fn before_proxy(req: Request,) -> RequestResult;
  #[allow(async_fn_in_trait)]
  fn after_proxy(resp: Response,) -> ResponseResult;
  #[allow(async_fn_in_trait)]
  fn on_stream_response_body(resp: Response,chunk: Option<BodyChunk>,) -> BodyResult;
  #[allow(async_fn_in_trait)]
  fn on_response(resp: Response,) -> ResponseResult;
}
#[doc(hidden)]

macro_rules! __export_snakeway_device_policy_1_0_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "snakeway:device/policy@1.0.0#on-request")]
    unsafe extern "C" fn export_on_request(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: *mut u8,arg7: usize,arg8: *mut u8,arg9: usize,arg10: *mut u8,arg11: usize,arg12: *mut u8,arg13: usize,arg14: *mut u8,arg15: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_on_request_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@1.0.0#on-request")]
    unsafe extern "C" fn _post_return_on_request(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_on_request::<$ty>(arg0) }
    }
    #[unsafe(export_name = "snakeway:device/policy@1.0.0#on-stream-request-body")]
    unsafe extern "C" fn export_on_stream_request_body(arg0: *mut u8,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_on_stream_request_body_cabi::<$ty>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@1.0.0#on-stream-request-body")]
    unsafe extern "C" fn _post_return_on_stream_request_body(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_on_stream_request_body::<$ty>(arg0) }
    }
    #[unsafe(export_name = "snakeway:device/policy@1.0.0#before-proxy")]
    unsafe extern "C" fn export_before_proxy(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: *mut u8,arg7: usize,arg8: *mut u8,arg9: usize,arg10: *mut u8,arg11: usize,arg12: *mut u8,arg13: usize,arg14: *mut u8,arg15: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_before_proxy_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@1.0.0#before-proxy")]
    unsafe extern "C" fn _post_return_before_proxy(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_before_proxy::<$ty>(arg0) }
    }
    #[unsafe(export_name = "snakeway:device/policy@1.0.0#after-proxy")]
    unsafe extern "C" fn export_after_proxy(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_after_proxy_cabi::<$ty>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@1.0.0#after-proxy")]
    unsafe extern "C" fn _post_return_after_proxy(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_after_proxy::<$ty>(arg0) }
    }
    #[unsafe(export_name = "snakeway:device/policy@1.0.0#on-stream-response-body")]
    unsafe extern "C" fn export_on_stream_response_body(arg0: i32,arg1: *mut u8,arg2: usize,arg3: i32,arg4: *mut u8,arg5: usize,arg6: i32,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_on_stream_response_body_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@1.0.0#on-stream-response-body")]
    unsafe extern "C" fn _post_return_on_stream_response_body(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_on_stream_response_body::<$ty>(arg0) }
    }
    #[unsafe(export_name = "snakeway:device/policy@1.0.0#on-response")]
    unsafe extern "C" fn export_on_response(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_on_response_cabi::<$ty>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@1.0.0#on-response")]
    unsafe extern "C" fn _post_return_on_response(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_on_response::<$ty>(arg0) }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_snakeway_device_policy_1_0_0_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 15*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 15*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub use alloc_crate::alloc;
  pub unsafe fn bool_lift(val: u8) -> bool {
    if cfg!(debug_assertions) {
      match val {
        0 => false,
        1 => true,
        _ => panic!("invalid bool discriminant"),
      }
    } else {
      val != 0
    }
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_device_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::snakeway::device::policy::__export_snakeway_device_policy_1_0_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::snakeway::device::policy);
  )
}
#[doc(inline)]
pub(crate) use __export_device_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.50.0:snakeway:device@1.0.0:device:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1416] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8b\x0a\x01A\x02\x01\
A\x0c\x01B\x09\x01ks\x01@\x01\x03keys\0\0\x04\0\x0aconfig-get\x01\x01\x01@\x02\x05\
level}\x07messages\x01\0\x04\0\x03log\x01\x02\x01@\x02\x04names\x05deltaw\x01\0\x04\
\0\x10metric-increment\x01\x03\x01@\0\0w\x04\0\x0aepoch-secs\x01\x04\x03\0\x1asn\
akeway:device/host@1.0.0\x05\0\x01B!\x01r\x02\x04names\x05values\x04\0\x06header\
\x03\0\0\x01q\x03\x03set\x01\x01\0\x06append\x01\x01\0\x06remove\x01s\0\x04\0\x09\
header-op\x03\0\x02\x01p\x01\x01r\x08\x06methods\x06schemes\x09authoritys\x0dori\
ginal-paths\x0aroute-paths\x05querys\x09client-ips\x07headers\x04\x04\0\x07reque\
st\x03\0\x05\x01r\x02\x06status{\x07headers\x04\x04\0\x08response\x03\0\x07\x01p\
}\x01r\x02\x04data\x09\x0dend-of-stream\x7f\x04\0\x0abody-chunk\x03\0\x0a\x01r\x03\
\x06status{\x07headers\x04\x04body\x09\x04\0\x12synthetic-response\x03\0\x0c\x01\
q\x03\x08continue\0\0\x05block\0\0\x07respond\x01\x0d\0\x04\0\x06action\x03\0\x0e\
\x01ks\x01p\x03\x01r\x03\x0eset-route-path\x10\x11set-upstream-path\x10\x03ops\x11\
\x04\0\x0drequest-patch\x03\0\x12\x01k{\x01r\x02\x0aset-status\x14\x03ops\x11\x04\
\0\x0eresponse-patch\x03\0\x15\x01k\x13\x01r\x02\x06action\x0f\x05patch\x17\x04\0\
\x0erequest-result\x03\0\x18\x01k\x16\x01r\x02\x06action\x0f\x05patch\x1a\x04\0\x0f\
response-result\x03\0\x1b\x01q\x04\x0bpassthrough\0\0\x07replace\x01\x09\0\x04dr\
op\0\0\x05block\0\0\x04\0\x0bbody-action\x03\0\x1d\x01r\x01\x06action\x1e\x04\0\x0b\
body-result\x03\0\x1f\x03\0\x1bsnakeway:device/types@1.0.0\x05\x01\x02\x03\0\x01\
\x07request\x02\x03\0\x01\x08response\x02\x03\0\x01\x0abody-chunk\x02\x03\0\x01\x0e\
request-result\x02\x03\0\x01\x0fresponse-result\x02\x03\0\x01\x0bbody-result\x01\
B\x17\x02\x03\x02\x01\x02\x04\0\x07request\x03\0\0\x02\x03\x02\x01\x03\x04\0\x08\
response\x03\0\x02\x02\x03\x02\x01\x04\x04\0\x0abody-chunk\x03\0\x04\x02\x03\x02\
\x01\x05\x04\0\x0erequest-result\x03\0\x06\x02\x03\x02\x01\x06\x04\0\x0fresponse\
-result\x03\0\x08\x02\x03\x02\x01\x07\x04\0\x0bbody-result\x03\0\x0a\x01@\x01\x03\
req\x01\0\x07\x04\0\x0aon-request\x01\x0c\x01k\x05\x01@\x02\x03req\x01\x05chunk\x0d\
\0\x0b\x04\0\x16on-stream-request-body\x01\x0e\x04\0\x0cbefore-proxy\x01\x0c\x01\
@\x01\x04resp\x03\0\x09\x04\0\x0bafter-proxy\x01\x0f\x01@\x02\x04resp\x03\x05chu\
nk\x0d\0\x0b\x04\0\x17on-stream-response-body\x01\x10\x04\0\x0bon-response\x01\x0f\
\x04\0\x1csnakeway:device/policy@1.0.0\x05\x08\x04\0\x1csnakeway:device/device@1\
.0.0\x04\0\x0b\x0c\x01\0\x06device\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\
\x0dwit-component\x070.243.0\x10wit-bindgen-rust\x060.50.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

