[package]
name = "snakeway-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
snakeway-acme = { workspace = true }
snakeway-conf = { workspace = true }
snakeway-engine = { workspace = true }
snakeway-net = { workspace = true }
snakeway-observability = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
arc-swap = { workspace = true }
brotli = { workspace = true }
bytes = { workspace = true }
flate2 = { workspace = true }
http = { workspace = true }
httpdate = { workspace = true }
mime_guess = { workspace = true }
nix = { workspace = true, features = ["signal"] }
percent-encoding = { workspace = true }
pingora = { workspace = true, features = ["proxy", "openssl_derived", "openssl"] }
openssl = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = [
    "fs",
    "rt",
    "sync",
    "signal",
    "macros",
    "tracing"
] }
tracing = { workspace = true }
opentelemetry = { workspace = true }
tracing-opentelemetry = { workspace = true }
hotpath = { workspace = true }