events {
    worker_connections 128;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;

        location / {
            try_files $uri $uri/ =404;
        }
    }

    server {
        listen 443 ssl;
        server_name localhost;
        root /usr/share/nginx/html;

        ssl_certificate /certs/server.pem;
        ssl_certificate_key /certs/server.key;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
