[package]
name = "confval-derive"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Derive macros for confval"
repository = "https://github.com/snakewayhq/snakeway"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
