// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod snakeway {
    pub mod device {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod policy {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        /// HTTP header
        #[derive(Clone)]
        pub struct Header {
          pub name: _rt::String,
          pub value: _rt::String,
        }
        impl ::core::fmt::Debug for Header {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Header").field("name", &self.name).field("value", &self.value).finish()
          }
        }
        /// Request snapshot passed to devices (read-only)
        #[derive(Clone)]
        pub struct Request {
          /// Original request path as received
          pub original_path: _rt::String,
          /// Canonical path currently used for routing
          pub route_path: _rt::String,
          /// Headers at this stage of the pipeline
          pub headers: _rt::Vec::<Header>,
        }
        impl ::core::fmt::Debug for Request {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Request").field("original-path", &self.original_path).field("route-path", &self.route_path).field("headers", &self.headers).finish()
          }
        }
        /// Response snapshot passed to devices (read-only)
        #[derive(Clone)]
        pub struct Response {
          pub status: u16,
          pub headers: _rt::Vec::<Header>,
        }
        impl ::core::fmt::Debug for Response {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("Response").field("status", &self.status).field("headers", &self.headers).finish()
          }
        }
        /// Explicit request mutation intent
        #[derive(Clone)]
        pub struct RequestPatch {
          /// Change the path used for routing (forces re-routing)
          pub set_route_path: Option<_rt::String>,
          /// Override the path sent to the upstream (does not affect routing)
          pub set_upstream_path: Option<_rt::String>,
          /// Headers to add or overwrite
          pub set_headers: _rt::Vec::<Header>,
          /// Headers to remove
          pub remove_headers: _rt::Vec::<_rt::String>,
        }
        impl ::core::fmt::Debug for RequestPatch {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("RequestPatch").field("set-route-path", &self.set_route_path).field("set-upstream-path", &self.set_upstream_path).field("set-headers", &self.set_headers).field("remove-headers", &self.remove_headers).finish()
          }
        }
        /// Explicit response mutation intent
        #[derive(Clone)]
        pub struct ResponsePatch {
          /// Override response status
          pub set_status: Option<u16>,
          /// Headers to add or overwrite
          pub set_headers: _rt::Vec::<Header>,
          /// Headers to remove
          pub remove_headers: _rt::Vec::<_rt::String>,
        }
        impl ::core::fmt::Debug for ResponsePatch {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("ResponsePatch").field("set-status", &self.set_status).field("set-headers", &self.set_headers).field("remove-headers", &self.remove_headers).finish()
          }
        }
        /// Device decision
        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum Decision {
          Continue,
          Block,
        }
        impl ::core::fmt::Debug for Decision {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              Decision::Continue => {
                f.debug_tuple("Decision::Continue").finish()
              }
              Decision::Block => {
                f.debug_tuple("Decision::Block").finish()
              }
            }
          }
        }

        impl Decision{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> Decision{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => Decision::Continue,
              1 => Decision::Block,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        /// Result of a request-phase hook
        #[derive(Clone)]
        pub struct RequestResult {
          pub decision: Decision,
          pub patch: Option<RequestPatch>,
        }
        impl ::core::fmt::Debug for RequestResult {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("RequestResult").field("decision", &self.decision).field("patch", &self.patch).finish()
          }
        }
        /// Result of a response-phase hook
        #[derive(Clone)]
        pub struct ResponseResult {
          pub decision: Decision,
          pub patch: Option<ResponsePatch>,
        }
        impl ::core::fmt::Debug for ResponseResult {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("ResponseResult").field("decision", &self.decision).field("patch", &self.patch).finish()
          }
        }
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_on_request_cabi<T: Guest>(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result9 = {
          let len0 = arg1;
          let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
          let len1 = arg3;
          let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
          let base8 = arg4;
          let len8 = arg5;
          let mut result8 = _rt::Vec::with_capacity(len8);
          for i in 0..len8 {
            let base = base8.add(i * (4*::core::mem::size_of::<*const u8>()));
            let e8 = {
              let l2 = *base.add(0).cast::<*mut u8>();
              let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len4 = l3;
              let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
              let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len7 = l6;
              let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

              Header{
                name: _rt::string_lift(bytes4),
                value: _rt::string_lift(bytes7),
              }
            };
            result8.push(e8);
          }
          _rt::cabi_dealloc(base8, len8 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          T::on_request(Request{
            original_path: _rt::string_lift(bytes0),
            route_path: _rt::string_lift(bytes1),
            headers: result8,
          })
        };
        let ptr10 = (&raw mut _RET_AREA.0).cast::<u8>();
        let RequestResult{ decision:decision11, patch:patch11, } = result9;
        *ptr10.add(0).cast::<u8>() = (decision11.clone() as i32) as u8;
        match patch11 {
          Some(e) => {
            *ptr10.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let RequestPatch{ set_route_path:set_route_path12, set_upstream_path:set_upstream_path12, set_headers:set_headers12, remove_headers:remove_headers12, } = e;
            match set_route_path12 {
              Some(e) => {
                *ptr10.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                let vec13 = (e.into_bytes()).into_boxed_slice();
                let ptr13 = vec13.as_ptr().cast::<u8>();
                let len13 = vec13.len();
                ::core::mem::forget(vec13);
                *ptr10.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
                *ptr10.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr13.cast_mut();
              },
              None => {
                {
                  *ptr10.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                }
              },
            };match set_upstream_path12 {
              Some(e) => {
                *ptr10.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
                let vec14 = (e.into_bytes()).into_boxed_slice();
                let ptr14 = vec14.as_ptr().cast::<u8>();
                let len14 = vec14.len();
                ::core::mem::forget(vec14);
                *ptr10.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
                *ptr10.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr14.cast_mut();
              },
              None => {
                {
                  *ptr10.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
                }
              },
            };let vec18 = set_headers12;
            let len18 = vec18.len();
            let layout18 = _rt::alloc::Layout::from_size_align(vec18.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
            let (result18, _cleanup18) = wit_bindgen::rt::Cleanup::new(layout18);if let Some(cleanup) = _cleanup18 { cleanup.forget(); }
            for (i, e) in vec18.into_iter().enumerate() {
              let base = result18.add(i * (4*::core::mem::size_of::<*const u8>()));
              {
                let Header{ name:name15, value:value15, } = e;
                let vec16 = (name15.into_bytes()).into_boxed_slice();
                let ptr16 = vec16.as_ptr().cast::<u8>();
                let len16 = vec16.len();
                ::core::mem::forget(vec16);
                *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len16;
                *base.add(0).cast::<*mut u8>() = ptr16.cast_mut();
                let vec17 = (value15.into_bytes()).into_boxed_slice();
                let ptr17 = vec17.as_ptr().cast::<u8>();
                let len17 = vec17.len();
                ::core::mem::forget(vec17);
                *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len17;
                *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr17.cast_mut();
              }
            }
            *ptr10.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>() = len18;
            *ptr10.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result18;
            let vec20 = remove_headers12;
            let len20 = vec20.len();
            let layout20 = _rt::alloc::Layout::from_size_align(vec20.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
            let (result20, _cleanup20) = wit_bindgen::rt::Cleanup::new(layout20);if let Some(cleanup) = _cleanup20 { cleanup.forget(); }
            for (i, e) in vec20.into_iter().enumerate() {
              let base = result20.add(i * (2*::core::mem::size_of::<*const u8>()));
              {
                let vec19 = (e.into_bytes()).into_boxed_slice();
                let ptr19 = vec19.as_ptr().cast::<u8>();
                let len19 = vec19.len();
                ::core::mem::forget(vec19);
                *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len19;
                *base.add(0).cast::<*mut u8>() = ptr19.cast_mut();
              }
            }
            *ptr10.add(11*::core::mem::size_of::<*const u8>()).cast::<usize>() = len20;
            *ptr10.add(10*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result20;
          },
          None => {
            {
              *ptr10.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };ptr10
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_on_request<T: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = i32::from(*arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
        match l0 {
          0 => (),
          _ => {
            let l1 = i32::from(*arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>());
            match l1 {
              0 => (),
              _ => {
                let l2 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l3 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l2, l3, 1);
              },
            }
            let l4 = i32::from(*arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>());
            match l4 {
              0 => (),
              _ => {
                let l5 = *arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l6 = *arg0.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l5, l6, 1);
              },
            }
            let l7 = *arg0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l8 = *arg0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base13 = l7;
            let len13 = l8;
            for i in 0..len13 {
              let base = base13.add(i * (4*::core::mem::size_of::<*const u8>()));
              {
                let l9 = *base.add(0).cast::<*mut u8>();
                let l10 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l9, l10, 1);
                let l11 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l12 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l11, l12, 1);
              }
            }
            _rt::cabi_dealloc(base13, len13 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
            let l14 = *arg0.add(10*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l15 = *arg0.add(11*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base18 = l14;
            let len18 = l15;
            for i in 0..len18 {
              let base = base18.add(i * (2*::core::mem::size_of::<*const u8>()));
              {
                let l16 = *base.add(0).cast::<*mut u8>();
                let l17 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                _rt::cabi_dealloc(l16, l17, 1);
              }
            }
            _rt::cabi_dealloc(base18, len18 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          },
        }
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_before_proxy_cabi<T: Guest>(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result9 = {
        let len0 = arg1;
        let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
        let len1 = arg3;
        let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
        let base8 = arg4;
        let len8 = arg5;
        let mut result8 = _rt::Vec::with_capacity(len8);
        for i in 0..len8 {
          let base = base8.add(i * (4*::core::mem::size_of::<*const u8>()));
          let e8 = {
            let l2 = *base.add(0).cast::<*mut u8>();
            let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len4 = l3;
            let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
            let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len7 = l6;
            let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

            Header{
              name: _rt::string_lift(bytes4),
              value: _rt::string_lift(bytes7),
            }
          };
          result8.push(e8);
        }
        _rt::cabi_dealloc(base8, len8 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        T::before_proxy(Request{
          original_path: _rt::string_lift(bytes0),
          route_path: _rt::string_lift(bytes1),
          headers: result8,
        })
      };
      let ptr10 = (&raw mut _RET_AREA.0).cast::<u8>();
      let RequestResult{ decision:decision11, patch:patch11, } = result9;
      *ptr10.add(0).cast::<u8>() = (decision11.clone() as i32) as u8;
      match patch11 {
        Some(e) => {
          *ptr10.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
          let RequestPatch{ set_route_path:set_route_path12, set_upstream_path:set_upstream_path12, set_headers:set_headers12, remove_headers:remove_headers12, } = e;
          match set_route_path12 {
            Some(e) => {
              *ptr10.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
              let vec13 = (e.into_bytes()).into_boxed_slice();
              let ptr13 = vec13.as_ptr().cast::<u8>();
              let len13 = vec13.len();
              ::core::mem::forget(vec13);
              *ptr10.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
              *ptr10.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr13.cast_mut();
            },
            None => {
              {
                *ptr10.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
              }
            },
          };match set_upstream_path12 {
            Some(e) => {
              *ptr10.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
              let vec14 = (e.into_bytes()).into_boxed_slice();
              let ptr14 = vec14.as_ptr().cast::<u8>();
              let len14 = vec14.len();
              ::core::mem::forget(vec14);
              *ptr10.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
              *ptr10.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr14.cast_mut();
            },
            None => {
              {
                *ptr10.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
              }
            },
          };let vec18 = set_headers12;
          let len18 = vec18.len();
          let layout18 = _rt::alloc::Layout::from_size_align(vec18.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
          let (result18, _cleanup18) = wit_bindgen::rt::Cleanup::new(layout18);if let Some(cleanup) = _cleanup18 { cleanup.forget(); }
          for (i, e) in vec18.into_iter().enumerate() {
            let base = result18.add(i * (4*::core::mem::size_of::<*const u8>()));
            {
              let Header{ name:name15, value:value15, } = e;
              let vec16 = (name15.into_bytes()).into_boxed_slice();
              let ptr16 = vec16.as_ptr().cast::<u8>();
              let len16 = vec16.len();
              ::core::mem::forget(vec16);
              *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len16;
              *base.add(0).cast::<*mut u8>() = ptr16.cast_mut();
              let vec17 = (value15.into_bytes()).into_boxed_slice();
              let ptr17 = vec17.as_ptr().cast::<u8>();
              let len17 = vec17.len();
              ::core::mem::forget(vec17);
              *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len17;
              *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr17.cast_mut();
            }
          }
          *ptr10.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>() = len18;
          *ptr10.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result18;
          let vec20 = remove_headers12;
          let len20 = vec20.len();
          let layout20 = _rt::alloc::Layout::from_size_align(vec20.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
          let (result20, _cleanup20) = wit_bindgen::rt::Cleanup::new(layout20);if let Some(cleanup) = _cleanup20 { cleanup.forget(); }
          for (i, e) in vec20.into_iter().enumerate() {
            let base = result20.add(i * (2*::core::mem::size_of::<*const u8>()));
            {
              let vec19 = (e.into_bytes()).into_boxed_slice();
              let ptr19 = vec19.as_ptr().cast::<u8>();
              let len19 = vec19.len();
              ::core::mem::forget(vec19);
              *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len19;
              *base.add(0).cast::<*mut u8>() = ptr19.cast_mut();
            }
          }
          *ptr10.add(11*::core::mem::size_of::<*const u8>()).cast::<usize>() = len20;
          *ptr10.add(10*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result20;
        },
        None => {
          {
            *ptr10.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
          }
        },
      };ptr10
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_before_proxy<T: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
      match l0 {
        0 => (),
        _ => {
          let l1 = i32::from(*arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l1 {
            0 => (),
            _ => {
              let l2 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l3 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l2, l3, 1);
            },
          }
          let l4 = i32::from(*arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l4 {
            0 => (),
            _ => {
              let l5 = *arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l6 = *arg0.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l5, l6, 1);
            },
          }
          let l7 = *arg0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l8 = *arg0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base13 = l7;
          let len13 = l8;
          for i in 0..len13 {
            let base = base13.add(i * (4*::core::mem::size_of::<*const u8>()));
            {
              let l9 = *base.add(0).cast::<*mut u8>();
              let l10 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l9, l10, 1);
              let l11 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l12 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l11, l12, 1);
            }
          }
          _rt::cabi_dealloc(base13, len13 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let l14 = *arg0.add(10*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l15 = *arg0.add(11*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base18 = l14;
          let len18 = l15;
          for i in 0..len18 {
            let base = base18.add(i * (2*::core::mem::size_of::<*const u8>()));
            {
              let l16 = *base.add(0).cast::<*mut u8>();
              let l17 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l16, l17, 1);
            }
          }
          _rt::cabi_dealloc(base18, len18 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        },
      }
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_after_proxy_cabi<T: Guest>(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();let result7 = {
      let base6 = arg1;
      let len6 = arg2;
      let mut result6 = _rt::Vec::with_capacity(len6);
      for i in 0..len6 {
        let base = base6.add(i * (4*::core::mem::size_of::<*const u8>()));
        let e6 = {
          let l0 = *base.add(0).cast::<*mut u8>();
          let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len2 = l1;
          let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
          let l3 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l4 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len5 = l4;
          let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

          Header{
            name: _rt::string_lift(bytes2),
            value: _rt::string_lift(bytes5),
          }
        };
        result6.push(e6);
      }
      _rt::cabi_dealloc(base6, len6 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      T::after_proxy(Response{
        status: arg0 as u16,
        headers: result6,
      })
    };
    let ptr8 = (&raw mut _RET_AREA.0).cast::<u8>();
    let ResponseResult{ decision:decision9, patch:patch9, } = result7;
    *ptr8.add(0).cast::<u8>() = (decision9.clone() as i32) as u8;
    match patch9 {
      Some(e) => {
        *ptr8.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
        let ResponsePatch{ set_status:set_status10, set_headers:set_headers10, remove_headers:remove_headers10, } = e;
        match set_status10 {
          Some(e) => {
            *ptr8.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            *ptr8.add(2+2*::core::mem::size_of::<*const u8>()).cast::<u16>() = (_rt::as_i32(e)) as u16;
          },
          None => {
            {
              *ptr8.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
            }
          },
        };let vec14 = set_headers10;
        let len14 = vec14.len();
        let layout14 = _rt::alloc::Layout::from_size_align(vec14.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result14, _cleanup14) = wit_bindgen::rt::Cleanup::new(layout14);if let Some(cleanup) = _cleanup14 { cleanup.forget(); }
        for (i, e) in vec14.into_iter().enumerate() {
          let base = result14.add(i * (4*::core::mem::size_of::<*const u8>()));
          {
            let Header{ name:name11, value:value11, } = e;
            let vec12 = (name11.into_bytes()).into_boxed_slice();
            let ptr12 = vec12.as_ptr().cast::<u8>();
            let len12 = vec12.len();
            ::core::mem::forget(vec12);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len12;
            *base.add(0).cast::<*mut u8>() = ptr12.cast_mut();
            let vec13 = (value11.into_bytes()).into_boxed_slice();
            let ptr13 = vec13.as_ptr().cast::<u8>();
            let len13 = vec13.len();
            ::core::mem::forget(vec13);
            *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
            *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr13.cast_mut();
          }
        }
        *ptr8.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
        *ptr8.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result14;
        let vec16 = remove_headers10;
        let len16 = vec16.len();
        let layout16 = _rt::alloc::Layout::from_size_align(vec16.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result16, _cleanup16) = wit_bindgen::rt::Cleanup::new(layout16);if let Some(cleanup) = _cleanup16 { cleanup.forget(); }
        for (i, e) in vec16.into_iter().enumerate() {
          let base = result16.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let vec15 = (e.into_bytes()).into_boxed_slice();
            let ptr15 = vec15.as_ptr().cast::<u8>();
            let len15 = vec15.len();
            ::core::mem::forget(vec15);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
            *base.add(0).cast::<*mut u8>() = ptr15.cast_mut();
          }
        }
        *ptr8.add(6*::core::mem::size_of::<*const u8>()).cast::<usize>() = len16;
        *ptr8.add(5*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result16;
      },
      None => {
        {
          *ptr8.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
        }
      },
    };ptr8
  } }
  #[doc(hidden)]
  #[allow(non_snake_case)]
  pub unsafe fn __post_return_after_proxy<T: Guest>(arg0: *mut u8,) { unsafe {
    let l0 = i32::from(*arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
    match l0 {
      0 => (),
      _ => {
        let l1 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l2 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base7 = l1;
        let len7 = l2;
        for i in 0..len7 {
          let base = base7.add(i * (4*::core::mem::size_of::<*const u8>()));
          {
            let l3 = *base.add(0).cast::<*mut u8>();
            let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
            let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l5, l6, 1);
          }
        }
        _rt::cabi_dealloc(base7, len7 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        let l8 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l9 = *arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base12 = l8;
        let len12 = l9;
        for i in 0..len12 {
          let base = base12.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let l10 = *base.add(0).cast::<*mut u8>();
            let l11 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l10, l11, 1);
          }
        }
        _rt::cabi_dealloc(base12, len12 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      },
    }
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_on_response_cabi<T: Guest>(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();let result7 = {
    let base6 = arg1;
    let len6 = arg2;
    let mut result6 = _rt::Vec::with_capacity(len6);
    for i in 0..len6 {
      let base = base6.add(i * (4*::core::mem::size_of::<*const u8>()));
      let e6 = {
        let l0 = *base.add(0).cast::<*mut u8>();
        let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len2 = l1;
        let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
        let l3 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l4 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len5 = l4;
        let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

        Header{
          name: _rt::string_lift(bytes2),
          value: _rt::string_lift(bytes5),
        }
      };
      result6.push(e6);
    }
    _rt::cabi_dealloc(base6, len6 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    T::on_response(Response{
      status: arg0 as u16,
      headers: result6,
    })
  };
  let ptr8 = (&raw mut _RET_AREA.0).cast::<u8>();
  let ResponseResult{ decision:decision9, patch:patch9, } = result7;
  *ptr8.add(0).cast::<u8>() = (decision9.clone() as i32) as u8;
  match patch9 {
    Some(e) => {
      *ptr8.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
      let ResponsePatch{ set_status:set_status10, set_headers:set_headers10, remove_headers:remove_headers10, } = e;
      match set_status10 {
        Some(e) => {
          *ptr8.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
          *ptr8.add(2+2*::core::mem::size_of::<*const u8>()).cast::<u16>() = (_rt::as_i32(e)) as u16;
        },
        None => {
          {
            *ptr8.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
          }
        },
      };let vec14 = set_headers10;
      let len14 = vec14.len();
      let layout14 = _rt::alloc::Layout::from_size_align(vec14.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
      let (result14, _cleanup14) = wit_bindgen::rt::Cleanup::new(layout14);if let Some(cleanup) = _cleanup14 { cleanup.forget(); }
      for (i, e) in vec14.into_iter().enumerate() {
        let base = result14.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let Header{ name:name11, value:value11, } = e;
          let vec12 = (name11.into_bytes()).into_boxed_slice();
          let ptr12 = vec12.as_ptr().cast::<u8>();
          let len12 = vec12.len();
          ::core::mem::forget(vec12);
          *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len12;
          *base.add(0).cast::<*mut u8>() = ptr12.cast_mut();
          let vec13 = (value11.into_bytes()).into_boxed_slice();
          let ptr13 = vec13.as_ptr().cast::<u8>();
          let len13 = vec13.len();
          ::core::mem::forget(vec13);
          *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
          *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr13.cast_mut();
        }
      }
      *ptr8.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
      *ptr8.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result14;
      let vec16 = remove_headers10;
      let len16 = vec16.len();
      let layout16 = _rt::alloc::Layout::from_size_align(vec16.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
      let (result16, _cleanup16) = wit_bindgen::rt::Cleanup::new(layout16);if let Some(cleanup) = _cleanup16 { cleanup.forget(); }
      for (i, e) in vec16.into_iter().enumerate() {
        let base = result16.add(i * (2*::core::mem::size_of::<*const u8>()));
        {
          let vec15 = (e.into_bytes()).into_boxed_slice();
          let ptr15 = vec15.as_ptr().cast::<u8>();
          let len15 = vec15.len();
          ::core::mem::forget(vec15);
          *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
          *base.add(0).cast::<*mut u8>() = ptr15.cast_mut();
        }
      }
      *ptr8.add(6*::core::mem::size_of::<*const u8>()).cast::<usize>() = len16;
      *ptr8.add(5*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result16;
    },
    None => {
      {
        *ptr8.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
      }
    },
  };ptr8
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_on_response<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base7 = l1;
      let len7 = l2;
      for i in 0..len7 {
        let base = base7.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let l3 = *base.add(0).cast::<*mut u8>();
          let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l3, l4, 1);
          let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l5, l6, 1);
        }
      }
      _rt::cabi_dealloc(base7, len7 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      let l8 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l9 = *arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base12 = l8;
      let len12 = l9;
      for i in 0..len12 {
        let base = base12.add(i * (2*::core::mem::size_of::<*const u8>()));
        {
          let l10 = *base.add(0).cast::<*mut u8>();
          let l11 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l10, l11, 1);
        }
      }
      _rt::cabi_dealloc(base12, len12 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    },
  }
} }
pub trait Guest {
  /// Called immediately after request acceptance, before routing
  #[allow(async_fn_in_trait)]
  fn on_request(req: Request,) -> RequestResult;
  /// Called after routing but before proxying upstream
  #[allow(async_fn_in_trait)]
  fn before_proxy(req: Request,) -> RequestResult;
  /// Called after receiving the upstream response
  #[allow(async_fn_in_trait)]
  fn after_proxy(resp: Response,) -> ResponseResult;
  /// Called just before sending the response to the client
  #[allow(async_fn_in_trait)]
  fn on_response(resp: Response,) -> ResponseResult;
}
#[doc(hidden)]

macro_rules! __export_snakeway_device_policy_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "snakeway:device/policy@0.1.0#on-request")]
    unsafe extern "C" fn export_on_request(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_on_request_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@0.1.0#on-request")]
    unsafe extern "C" fn _post_return_on_request(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_on_request::<$ty>(arg0) }
    }
    #[unsafe(export_name = "snakeway:device/policy@0.1.0#before-proxy")]
    unsafe extern "C" fn export_before_proxy(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_before_proxy_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@0.1.0#before-proxy")]
    unsafe extern "C" fn _post_return_before_proxy(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_before_proxy::<$ty>(arg0) }
    }
    #[unsafe(export_name = "snakeway:device/policy@0.1.0#after-proxy")]
    unsafe extern "C" fn export_after_proxy(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_after_proxy_cabi::<$ty>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@0.1.0#after-proxy")]
    unsafe extern "C" fn _post_return_after_proxy(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_after_proxy::<$ty>(arg0) }
    }
    #[unsafe(export_name = "snakeway:device/policy@0.1.0#on-response")]
    unsafe extern "C" fn export_on_response(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_on_response_cabi::<$ty>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_snakeway:device/policy@0.1.0#on-response")]
    unsafe extern "C" fn _post_return_on_response(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_on_response::<$ty>(arg0) }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_snakeway_device_policy_0_1_0_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 12*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 12*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub use alloc_crate::alloc;

  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_snakeway_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::snakeway::device::policy::__export_snakeway_device_policy_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::snakeway::device::policy);
  )
}
#[doc(inline)]
pub(crate) use __export_snakeway_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.49.0:snakeway:device@0.1.0:snakeway:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 684] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xad\x04\x01A\x02\x01\
A\x02\x01B\x1c\x01r\x02\x04names\x05values\x04\0\x06header\x03\0\0\x01p\x01\x01r\
\x03\x0doriginal-paths\x0aroute-paths\x07headers\x02\x04\0\x07request\x03\0\x03\x01\
r\x02\x06status{\x07headers\x02\x04\0\x08response\x03\0\x05\x01ks\x01ps\x01r\x04\
\x0eset-route-path\x07\x11set-upstream-path\x07\x0bset-headers\x02\x0eremove-hea\
ders\x08\x04\0\x0drequest-patch\x03\0\x09\x01k{\x01r\x03\x0aset-status\x0b\x0bse\
t-headers\x02\x0eremove-headers\x08\x04\0\x0eresponse-patch\x03\0\x0c\x01m\x02\x08\
continue\x05block\x04\0\x08decision\x03\0\x0e\x01k\x0a\x01r\x02\x08decision\x0f\x05\
patch\x10\x04\0\x0erequest-result\x03\0\x11\x01k\x0d\x01r\x02\x08decision\x0f\x05\
patch\x13\x04\0\x0fresponse-result\x03\0\x14\x01@\x01\x03req\x04\0\x12\x04\0\x0a\
on-request\x01\x16\x04\0\x0cbefore-proxy\x01\x16\x01@\x01\x04resp\x06\0\x15\x04\0\
\x0bafter-proxy\x01\x17\x04\0\x0bon-response\x01\x17\x04\0\x1csnakeway:device/po\
licy@0.1.0\x05\0\x04\0\x1esnakeway:device/snakeway@0.1.0\x04\0\x0b\x0e\x01\0\x08\
snakeway\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.2\
43.0\x10wit-bindgen-rust\x060.49.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

