[package]
name = "snakeway-conf"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

[dependencies]
confval = { workspace = true }
glob = { workspace = true }
ipnet = { workspace = true, features = ["serde"] }
openssl = { workspace = true }
http = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
hcl-rs = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
smallvec = { workspace = true }
hotpath = { workspace = true }
secrecy = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }

[dev-dependencies]
rcgen = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["hcl-rs"]
