[package]
name = "snakeway-conf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glob = { workspace = true }
ipnet = { workspace = true, features = ["serde"] }
nix = { workspace = true, features = ["signal"] }
openssl = { workspace = true }
http = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
hcl-rs = { workspace = true }
owo-colors = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
rcgen = { workspace = true }
